name: sonic-client-web

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: login docker hub
        run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u zhouyixun --password-stdin
      - name: build docker image
        run: DOCKER_DEFAULT_PLATFORM="linux/arm64" docker build -f sonic-client-web/Dockerfile -t iceblacktea/sonic-client-web-arm64-base:v1.0.0 .
      - name: push docker image
        run: docker push iceblacktea/sonic-client-web-arm64-base:v1.0.0
