name: sonic-agent
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: login docker hub
        run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u iceblacktea --password-stdin
      - name: build docker image
        run: docker build --platform linux/arm64 -f sonic-agent/Dockerfile -t iceblacktea/sonic-agent-linux-arm64-base:v1.0.2 .
      - name: push docker image
        run: docker push iceblacktea/sonic-agent-linux-arm64-base:v1.0.2
